name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-18.04
    container: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-ubuntu-bionic-${{ matrix.bionic_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.8.2
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.9.4
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.10.4
            otp: 21.3.8.18
            bionic_version: 20200630
          - elixir: 1.11.0
            otp: 21.3.8.18
            bionic_version: 20200630
          - elixir: 1.11.0
            otp: 23.1.1
            bionic_version: 20200630

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix test
      - run: mix test.as_a_dep

  test-mysql:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:${{ matrix.mysql_version }}
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    container: elixir:${{ matrix.elixir_version }}-slim

    strategy:
      fail-fast: false
      matrix:
        mysql_version: ["5.7", "8.0"]
        elixir_version: [1.8, 1.9, 1.10, 1.11]

    steps:
      - name: Install MySQL Client
        run: |
          apt-get update
          apt-get install -y wget ca-certificates gnupg
          apt-key adv --recv-keys --keyserver keys.gnupg.net 8C718D3B5072E1F5
          echo "deb http://repo.mysql.com/apt/debian/ stretch mysql-${{ matrix.mysql_version }}" >> /etc/apt/sources.list.d/mysql.list
          apt-get update
          apt-get install --allow-unauthenticated -y mysql-client
          mysql --version
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          apt-get install -y git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: MYSQL_URL=root:root@mysql ECTO_ADAPTER=myxql mix test
  
  test-mssql:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:${{ matrix.mssql_version }}
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: some!Password
        ports:
          - 1433:1433

    strategy:
      matrix:
        mssql_version: ["2017-latest", "2019-latest"]
        include:
          - elixir: 1.8.2
            otp: 20.3.8.26
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.4
            otp: 21.3.8.18
          - elixir: 1.11.0
            otp: 21.3.8.18
          - elixir: 1.11.0
            otp: 23.1.1
        
    env:
      ACCEPT_EULA: Y
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install MsSql Client Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - run: |
          export PATH="/opt/mssql-tools/bin:$PATH"
          ECTO_ADAPTER=tds mix test
          
  test-pg:
    runs-on: ubuntu-18.04

    services:
      pg:
        image: postgres:${{ matrix.pg_version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-ubuntu-bionic-${{ matrix.bionic_version }}
      env:
        DEBIAN_FRONTEND: noninteractive

    strategy:
      fail-fast: false
      matrix:
        pg_version: ["9.5", "9.6", "11"]
        include:
          - elixir: 1.8.2
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.9.4
            otp: 20.3.8.26
            bionic_version: 20200403
          - elixir: 1.10.4
            otp: 21.3.8.18
            bionic_version: 20200630
          - elixir: 1.11.0
            otp: 21.3.8.18
            bionic_version: 20200630
          - elixir: 1.11.0
            otp: 23.1.1
            bionic_version: 20200630

        elixir: [1.11.0]
        otp: [23.1.1]
        bionic_version: [20200630]

    steps:
      - name: Install PG Client
        run: |
          apt-get update
          apt-get install -y curl gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main ${{ matrix.pg_version }}" >> /etc/apt/sources.list.d/pgdg.list
          apt-get update
          apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-contrib-${{ matrix.pg_version }}
          psql --version
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          apt-get install -y git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: PG_URL=postgres:postgres@pg ECTO_ADAPTER=pg mix test
